const colors = {
  light: {
    text: "#1F1F1F",
    tint: "#5455D4",
    background: "#F5F5F5",
    foreground: "#1F1F1F",
    card: "#FFFFFF",
    cardForeground: "#1F1F1F",
    primary: "#5455D4",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F0",
    secondaryForeground: "#1F1F1F",
    muted: "#F0F0F0",
    mutedForeground: "#757575",
    accent: "#FF6B6B",
    accentForeground: "#FFFFFF",
    destructive: "#D32F2F",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0E0",
    input: "#EEEEEE",
    toolbar: "#FFFFFF",
    urlBar: "#EFEFEF",
    progressBar: "#5455D4",
    tabBar: "#FFFFFF",
    incognito: "#1A1A2A",
    incognitoForeground: "#E8E8FF",
  },
  dark: {
    text: "#E3E3E3",
    tint: "#8B8CF8",
    background: "#111111",
    foreground: "#E3E3E3",
    card: "#1E1E1E",
    cardForeground: "#E3E3E3",
    primary: "#8B8CF8",
    primaryForeground: "#111111",
    secondary: "#2A2A2A",
    secondaryForeground: "#E3E3E3",
    muted: "#2A2A2A",
    mutedForeground: "#9E9E9E",
    accent: "#FF6B6B",
    accentForeground: "#FFFFFF",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#2A2A2A",
    toolbar: "#1E1E1E",
    urlBar: "#2A2A2A",
    progressBar: "#8B8CF8",
    tabBar: "#1E1E1E",
    incognito: "#0D0D0D",
    incognitoForeground: "#CCCCFF",
  },
  radius: 8,
};

export default colors;
