const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#5455D4",
    background: "#F2F2FA",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#5455D4",
    primaryForeground: "#FFFFFF",
    secondary: "#EBEBF6",
    secondaryForeground: "#1A1A2E",
    muted: "#EBEBF6",
    mutedForeground: "#8787A8",
    accent: "#FF6B6B",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0EE",
    input: "#E8E8F4",
    toolbar: "#FFFFFF",
    urlBar: "#EDEDF8",
    progressBar: "#5455D4",
    tabBar: "#FFFFFF",
    incognito: "#2D2D4E",
    incognitoForeground: "#FFFFFF",
  },
  dark: {
    text: "#E8E8F4",
    tint: "#8B8CF8",
    background: "#0D0D1C",
    foreground: "#E8E8F4",
    card: "#1A1A2E",
    cardForeground: "#E8E8F4",
    primary: "#8B8CF8",
    primaryForeground: "#0D0D1C",
    secondary: "#22223A",
    secondaryForeground: "#E8E8F4",
    muted: "#22223A",
    mutedForeground: "#6E6E8A",
    accent: "#FF6B6B",
    accentForeground: "#FFFFFF",
    destructive: "#FF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D2D50",
    input: "#22223A",
    toolbar: "#1A1A2E",
    urlBar: "#22223A",
    progressBar: "#8B8CF8",
    tabBar: "#1A1A2E",
    incognito: "#1A1A30",
    incognitoForeground: "#C8C8FF",
  },
  radius: 12,
};

export default colors;
