# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true
reactNativeArchitectures=arm64-v8a
newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=false
expo.gif.enabled=false
expo.webp.enabled=false
expo.webp.animated=false
expo.useLegacyPackaging=true
expo.edgeToEdgeEnabled=false
